.include <qdnix.hostinit.mk>

LICENSE = gpl3
MODULE =  gmake

CONFIGURE_ARGS = \
	--program-prefix=${TOOLS_PREFIX}g \
	--disable-nls

ALL_TARGET = all
INSTALL_TARGET = install
MAKE_PROGRAM=${TOOL_BMAKE}

.include "${.CURDIR}/../Makefile.gnuhost"
