MAN2 = intro.2 \
		brk.2 \
		chdir.2 \
		close.2 \
		dup.2 \
		exec.2 \
		exit.2 \
		fork.2 \
		fstat.2 \
		getpid.2 \
		kill.2 \
		link.2 \
		mkdir.2 \
		pipe.2 \
		unlink.2

.include <qdnix.man.mk>
