.TH HIER 7 "28 Thermidor CCXXX" "d0p1"
.SH NAME
hier \- layout of file systems
.SH SYNOPSIS
A sketch of the file system hierarchy.
.SH DESCRIPTION
.IP "/"
Root directory.
.IP "/bin/"
User utilities.
.IP "/dev/"
Block and character device files.
.IP "/etc/"
System configuration files and scripts.
.IP "/home/"
Default location for user home directories.
.IP "/root/"
Default home directory for the superuser.
.IP "/sbin/"
System daemon and utilities.
.IP "/share/"
Architecture independent data files.
.RS
.IP "calendar/"
Pre-fab calendar files
.IP "man/"
Manual pages.
.RE
.IP "/src/"
QDNix source files.

