.Dd "23 Germinal CCXXXII"
.Dt HIER 7
.Os QDNix
.Sh NAME
.Nm hier
.Nd layout of file systems
.Sh DESCRIPTION
A sketch of the file system hierarchy.
.Bl -tag -width "/share/"
.It /
Root directory.
.It /bin/
User utilities.
.It /dev/
Block and character device files.
.It /etc/
System configuration files and scripts.
.It /home/
Default location for user home directories.
.It /root/
Default home directory for the superuser.
.It /sbin/
System daemon and utilities.
.It /share/
Architecture independent data files.
.Pp
.Bl -tag -width calendar -compact
.It calendar/
Pre-fab calendar files
.It man/
Manual pages.
.El
.It /src/
QDNix source files.
.El
