QDNix: src/sys/dev/serial/8250.c File Reference
8250.c File Reference
#include <sys/machine/mmio.h>
#include <dev/serial/serial.h>
#include <dev/serial/8250.h>
#include "config.h"
Functions
static int serial_8250_is_buffer_empty (SerialDevice *dev)
static size_t serial_8250_write (void *raw, const char *str, size_t size)
static size_t serial_8250_read (void *raw, char *buff, size_t size)
void serial_8250_init (SerialDevice *dev)
Function Documentation
serial_8250_init()
void serial_8250_init (SerialDevice * dev)
Definition at line 50 of file 8250.c.
serial_8250_is_buffer_empty()
static int serial_8250_is_buffer_empty (SerialDevice * dev) static
Definition at line 9 of file 8250.c.
Referenced by serial_8250_write().
serial_8250_read()
static size_t serial_8250_read (void * raw, char * buff, size_t size) static
Definition at line 39 of file 8250.c.
Referenced by serial_8250_init().
serial_8250_write()
static size_t serial_8250_write (void * raw, const char * str, size_t size) static
Definition at line 16 of file 8250.c.
Referenced by serial_8250_init().