var annotated_dup =
[
    [ "Console", "structConsole.html", "structConsole" ],
    [ "ConsoleDevice", "structConsoleDevice.html", "structConsoleDevice" ],
    [ "Device", "structDevice.html", "structDevice" ],
    [ "Driver", "structDriver.html", "structDriver" ],
    [ "exec", "structexec.html", "structexec" ],
    [ "FDTEntry", "structFDTEntry.html", "structFDTEntry" ],
    [ "FDTHeader", "structFDTHeader.html", "structFDTHeader" ],
    [ "FDTProp", "structFDTProp.html", "structFDTProp" ],
    [ "GpioRegister", "structGpioRegister.html", "structGpioRegister" ],
    [ "kinfo", "structkinfo.html", null ],
    [ "minix_dir_entry", "structminix__dir__entry.html", "structminix__dir__entry" ],
    [ "minix_inode", "structminix__inode.html", "structminix__inode" ],
    [ "minix_super_block", "structminix__super__block.html", "structminix__super__block" ],
    [ "Multiboot", "structMultiboot.html", "structMultiboot" ],
    [ "MultibootDriveEntry", "structMultibootDriveEntry.html", "structMultibootDriveEntry" ],
    [ "MultibootMemEntry", "structMultibootMemEntry.html", "structMultibootMemEntry" ],
    [ "nlist", "structnlist.html", "structnlist" ],
    [ "relocation_info", "structrelocation__info.html", "structrelocation__info" ],
    [ "SerialDevice", "structSerialDevice.html", "structSerialDevice" ],
    [ "stat", "structstat.html", "structstat" ],
    [ "TTYDevice", "structTTYDevice.html", "structTTYDevice" ],
    [ "UARTRegister", "structUARTRegister.html", "structUARTRegister" ],
    [ "utsname", "structutsname.html", "structutsname" ],
    [ "VFS", "structVFS.html", "structVFS" ],
    [ "VSFOps", "structVSFOps.html", "structVSFOps" ],
    [ "xfs_btree_lblock", "structxfs__btree__lblock.html", null ],
    [ "xfs_btree_sblock", "structxfs__btree__sblock.html", null ],
    [ "xfs_da3_blkinfo", "structxfs__da3__blkinfo.html", null ],
    [ "xfs_da3_intnode", "structxfs__da3__intnode.html", "structxfs__da3__intnode" ],
    [ "xfs_da_blkinfo_t", "structxfs__da__blkinfo__t.html", null ],
    [ "xfs_da_intnode_t", "structxfs__da__intnode__t.html", "structxfs__da__intnode__t" ],
    [ "xfs_legacy_timestamp", "structxfs__legacy__timestamp.html", "structxfs__legacy__timestamp" ],
    [ "xfs_sb", "structxfs__sb.html", "structxfs__sb" ],
    [ "zealfs_dir_entry", "structzealfs__dir__entry.html", "structzealfs__dir__entry" ],
    [ "ZealFSHdr", "structZealFSHdr.html", "structZealFSHdr" ]
];