QDNix: src/sys/sys/console.h File Reference
console.h File Reference
#include <stddef.h>
#include <dev/device.h>
Data Structures
struct Console
Functions
void console_flush (void)
void console_putchar (char c)
void console_setup (Device *dev)
Function Documentation
console_flush()
void console_flush (void)
Definition at line 15 of file console.c.
Referenced by console_putchar(), console_setup(), and printk().
console_putchar()
void console_putchar (char c)
Definition at line 26 of file console.c.
Referenced by printk(), printstr(), and printuint().
console_setup()
void console_setup (Device * dev)
Definition at line 43 of file console.c.