QDNix: src/sys/kern/console.c File Reference
console.c File Reference
#include "dev/device.h"
#include <stddef.h>
#include <stdint.h>
#include <sys/console.h>
Functions
void console_flush (void)
void console_putchar (char c)
void console_setup (Device *dev)
Variables
static Console * console = NULL
Function Documentation
console_flush()
void console_flush (void)
Definition at line 15 of file console.c.
Referenced by console_putchar(), console_setup(), and printk().
console_putchar()
void console_putchar (char c)
Definition at line 26 of file console.c.
Referenced by printk(), printstr(), and printuint().
console_setup()
void console_setup (Device * dev)
Definition at line 43 of file console.c.
Variable Documentation
console
Console* console = NULL static
Definition at line 12 of file console.c.
Referenced by console_flush(), console_putchar(), and console_setup().