QDNix: src/sys/sys/machine/mmio.h File Reference
mmio.h File Reference
#include <stdint.h>
Functions
static __inline__ void mmio_write8 (uintptr_t addr, uint8_t value)
static __inline__ uint8_t mmio_read8 (uintptr_t addr)
static __inline__ void mmio_write16 (uintptr_t addr, uint16_t value)
static __inline__ uint16_t mmio_read16 (uintptr_t addr)
static __inline__ void mmio_write32 (uintptr_t addr, uint32_t value)
static __inline__ uint32_t mmio_read32 (uintptr_t addr)
Function Documentation
mmio_read16()
static __inline__ uint16_t mmio_read16 (uintptr_t addr) static
Definition at line 25 of file mmio.h.
mmio_read32()
static __inline__ uint32_t mmio_read32 (uintptr_t addr) static
Definition at line 37 of file mmio.h.
Referenced by ccu_init_clock(), and uart_putchar().
mmio_read8()
static __inline__ uint8_t mmio_read8 (uintptr_t addr) static
Definition at line 13 of file mmio.h.
Referenced by serial_8250_is_buffer_empty(), and uart_putchar().
mmio_write16()
static __inline__ void mmio_write16 (uintptr_t addr, uint16_t value) static
Definition at line 19 of file mmio.h.
mmio_write32()
static __inline__ void mmio_write32 (uintptr_t addr, uint32_t value) static
Definition at line 31 of file mmio.h.
Referenced by ccu_init_clock(), and uart_putchar().
mmio_write8()
static __inline__ void mmio_write8 (uintptr_t addr, uint8_t value) static
Definition at line 7 of file mmio.h.
Referenced by serial_8250_init(), serial_8250_write(), and uart_putchar().