QDNix: SerialDevice Struct Reference
SerialDevice Struct Reference
#include <serial.h>
Data Fields
void(* init)(void *)
size_t(* write)(void *, const char *, size_t)
size_t(* read)(void *, char *, size_t)
uintptr_t io_base
int irq
uint8_t reg_offset
uint32_t beaudrate
Detailed Description
Definition at line 37 of file serial.h.
Field Documentation
beaudrate
uint32_t beaudrate
Definition at line 45 of file serial.h.
init
void(* init) (void *)
Definition at line 38 of file serial.h.
Referenced by platform_init().
io_base
uintptr_t io_base
Definition at line 42 of file serial.h.
irq
int irq
Definition at line 43 of file serial.h.
read
size_t(* read) (void *, char *, size_t)
Definition at line 40 of file serial.h.
Referenced by console_setup().
reg_offset
uint8_t reg_offset
Definition at line 44 of file serial.h.
write
size_t(* write) (void *, const char *, size_t)
Definition at line 39 of file serial.h.
Referenced by console_setup().
The documentation for this struct was generated from the following file:
src/sys/dev/tty/serial/serial.h