.TH CHDIR 2 "28 Thermidor CCXXX" "d0p1"
.SH NAME
chdir \- change current working directory
.SH SYNOPSIS
.PP
.nf
.BI "int chdir(const char *" path);
.fi
.PP
.SH DESCRIPTION
.BR chdir ()
changes the current working directory of the calling process to the directory specified in path.
.IR path .
.SH RETURN VALUES
.BR chdir ()
return zero on success.
On error, \-1 is returned.
