.Dd "23 Germinal CCXXXII"
.Dt CHDIR 2
.Os QDNix
.Sh NAME
.Nm chdir
.Nd change current working directory
.Sh SYNOPSIS
.In
.Ft int
.Fn chdir "const char *path"
.Sh DESCRIPTION
.Fn chdir
changes the current working directory of the calling process to the directory specified in path.
.Sh RETURN VALUES
.Fn chdir
return zero on success.
On error, \-1 is returned.
