.TH MKDIR 2 "30 Pluviôse CCXXXI" "d0p1"
.SH NAME
mkdir \- create a directory
.SH SYNOPSIS
.PP
.nf
.BI "int mkdir(const char *" path);
.fi
.PP
.SH DESCRIPTION
.BR mkdir ()
attempts to create a directory named
.IR path .
.SH RETURN VALUES
.BR mkdir ()
return zero on success.
On error, \-1 is returned.
