name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine: ['i386']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: .tools
          key: ${{ runner.os }}-tools

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential python3 
        
      - name: build tools
        run: |
          ./build.sh tools

      - name: build distrib
        run: |
          ./build.sh build
