name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: build/host
          key: ${{ runner.os }}-tools

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pandoc imagemagick doxygen texlive-binaries build-essential sassc

      - name: Generate
        run: sh build.sh www

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/www/html
          cname: qdnix.d0p1.eu
