name: Documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pandoc imagemagick doxygen texlive-binaries build-essential

      - name: Generate
        run: sh build.sh www

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/www/html
          cname: qdnix.d0p1.eu
