
name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libcmocka-dev
          sudo pip install kconfiglib
      - name: Build and run tests
        run: |
          make defconfig
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
